[tool.poetry]
name = "epochutil"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
statsmodels = "^0.13.5"
numpy = "^1.24.2"
pandas = "^1.5.3"
scipy = ">=1,<1.9"
copula-wrapper = { git = "https://github.com/tadamcz/copula-wrapper", rev = "e5ab1a2b5bbc3df06f3ea7648a7784b18d8759bf" }
nonstd = { git = "https://github.com/tadamcz/nonstd", rev = "4b6152626248495b15d4318330d83e42625010ba" }

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
